### PR TITLE
Updated Subsystems part

### PR DESCRIPTION
**Pull request by vishalsingh2972**
Made the changes requested - no inline css, subtler colors, added hover to make it look more responsive.
image

P.S: Default color light green & light brown is hover

### CODE REVIEW

**Comment by vishalsingh2972** [comment]
@abhishekshree  can you review this PR

**Comment by abhishekshree** [comment]
attach a screenshot please

**Comment by abhishekshree** [comment]
I am looking for a better way to put it up and just changing the colors are not helping @vishalsingh2972 

Can you think of something better? You can take time if you want

**Comment by vishalsingh2972** [comment]
> I am looking for a better way to put it up and just changing the colors are not helping @vishalsingh2972 
> 
> Can you think of something better? You can take time if you want

Anything specific that you want, new to JS so you being "very" specific would really help me a lot ✌️

**Comment by abhishekshree** [comment]
> > I am looking for a better way to put it up and just changing the colors are not helping @vishalsingh2972
> > Can you think of something better? You can take time if you want
> 
> Anything specific that you want, new to JS so you being "very" specific would really help me a lot ✌️

I mentioned about about cuauv.org right? You can follow something from that they did in their team section, I will try to put up some exact idea about how it should look like in a while if you want that

**Comment by vishalsingh2972** [comment]
> > > I am looking for a better way to put it up and just changing the colors are not helping @vishalsingh2972
> > > Can you think of something better? You can take time if you want
> > 
> > Anything specific that you want, new to JS so you being "very" specific would really help me a lot ✌️
> 
> I mentioned about about cuauv.org right? You can follow something from that they did in their team section, I will try to put up some exact idea about how it should look like in a while if you want that

I tried but couldn't get the shade that they used so used basic subtle colors instead...yeah please do put up the idea👍

**Comment by abhishekshree** [comment]
image
Something of this sort with white and blue @vishalsingh2972

**Pull request closed without merging**
