### PR TITLE
Team Page pull Request

### PR DESCRIPTION
**Pull request by umeshmeena141**
Team page for 17-present session with name teampage17.html has been added and team member list with other details is in the teammembers.js.

### CODE REVIEW

**Comment by Mayankm96** [comment]
@umeshmeena141 there seem to be a few merge conflicts over here. Could you resolve them and send a pull request again?

**Comment by Mayankm96** [comment]
There seems to be something wrong with the image size. You can use the same template like we have in the homepage to put the photo as the bg image in that part. 

issue

**Comment by Mayankm96** [comment]
You could also improve upon the color scheme thaat is there and decrease the size of the boxes for alumni information.

**Comment by umeshmeena141** [comment]
Conflicts are now resolved

**Comment by Mayankm96** [comment]
Looks pretty cool now! :D

A few changes that might be useful is: 
1. fix the alignment of the text and the box in the team 2017-18 page 
2. You can remove the photo from the alumni page as it looks kinda weird since it spans across the entire page. Also the font 'Our Alumni' should be made central and  be changed to match the rest of the website template. 
3. There is a jump in the white bar that is present in the alumni page. It should be made more smooth. 
4. There should be a margin in the left and right side of the page. Right now it looks too packed.

**Comment by Mayankm96** [comment]
@umeshmeena141 I reviewed the changes right now. In teampage the animation is not smooth. There seems to be some kind of screen fishing occurring. Also when I am on teampage then the nav bar on top is white on HOME instead of TEAM.

**Comment by Mayankm96** [comment]
@umeshmeena141 the new animation again, looks a bit slow for normal users to view the website. The previous one looked better in my opinion. Also there are conflicts that need `git pull` :)

**Pull request merged**
