### PR TITLE
[add] BlogsPage: migrated to functional components #125

### PR DESCRIPTION
**Pull request by sammaji**
Created a new file `BlogsPage.rfc.jsx` in the file that use functional components ( issue #125 )

### CODE REVIEW

**Review by abhishekshree — COMMENTED** [review]
Is src/assets/img/software.jpeg:Zone.Identifier needed?

**Comment by sammaji** [comment]
Its not needed.

**Review by abhishekshree — CHANGES_REQUESTED** [review]
any specific requirements of the ".rfc"? if not, please remove the original blog page component and update the PR. Also if you could attach a screenshot with the page up and running properly it'll be helpful

**Comment by abhishekshree** [comment]
Then we are good to go.

**Comment by sammaji** [comment]
Ok @abhishekshree I implemented the changes. The website is working. Here's the screenshot.
Screenshot 2023-01-05 174801

**Comment by sammaji** [comment]
hey @abhishekshree made the changes you requested. review them

**Review by abhishekshree — APPROVED** [review]

**Comment by abhishekshree** [comment]
lgtm for now, merging

**Pull request merged**
